common/modules/yii2-core/models/CoreFields.php
<?php

namespace msoft\core\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\AttributeBehavior;
use msoft\behaviors\CoreMultiValueBehavior;
use msoft\utils\CoreUtility;

/**
 * This is the model class for table "core_fields".
 *
 * @property string $field_code
 * @property integer $field_internal
 * @property string $field_class
 * @property string $field_name
 * @property string $field_meta
 * @property string $field_description
 */
class CoreFields extends \yii\db\ActiveRecord {

    public function behaviors() {
		return [
			[
				'class' => AttributeBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_INIT => 'field_internal',
				],
				'value' => function ($event) {
					return 1;
				},
			],
			[
				'class' => CoreMultiValueBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_AFTER_FIND => 'field_meta',
				],
				'value' => function ($event) {
					return CoreUtility::string2strArray($event->sender[$event->data]);
				},
			],
			[
				'class' => CoreMultiValueBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => 'field_meta',
					ActiveRecord::EVENT_BEFORE_UPDATE => 'field_meta',
				],
				'value' => function ($event) {
					return CoreUtility::strArray2String($event->sender[$event->data]);
				},
			],
		];
	}
	/**
	 * @inheritdoc
	 */
	public static function tableName() {
		return 'core_fields';
	}

	/**
	 * @inheritdoc
	 */
	public function rules() {
		return [
			[['field_code', 'field_name'], 'required'],
			[['field_code'], 'unique'],
			[['field_internal'], 'integer'],
			[['field_meta', 'field_description'], 'string'],
			[['field_code'], 'string', 'max' => 20],
			[['field_name'], 'string', 'max' => 30],
			[['field_class'], 'string', 'max' => 80]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels() {
		return [
			'field_code' => Yii::t('core', 'Code'),
			'field_internal' => Yii::t('core', 'Internal'),
			'field_class' => Yii::t('core', 'Class'),
			'field_name' => Yii::t('core', 'Function'),
			'field_meta' => Yii::t('core', 'Option'),
			'field_description' => Yii::t('core', 'Description'),
		];
	}

}

common/modules/yii2-core/controllers/CoreFieldsController.php
<?php

namespace msoft\core\controllers;

use Yii;
use msoft\core\models\CoreFields;
use msoft\core\models\CoreFieldsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Response;
use msoft\helpers\Html;

/**
 * CoreFieldsController implements the CRUD actions for CoreFields model.
 */
class CoreFieldsController extends Controller {

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'actions' => ['index', 'view'],
						'roles' => ['?', '@'],
					],
					[
						'allow' => true,
						'actions' => ['view', 'create', 'update', 'delete', 'deletes'],
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}

	public function beforeAction($action) {
		if (parent::beforeAction($action)) {
			if (in_array($action->id, array('create', 'update'))) {
				
			}
			return true;
		} else {
			return false;
		}
	}
	
	/**
	 * Lists all CoreFields models.
	 * @return mixed
	 */
	public function actionIndex() {
		$searchModel = new CoreFieldsSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
		return $this->render('index', [
					'searchModel' => $searchModel,
					'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Displays a single CoreFields model.
	 * @param string $id
	 * @return mixed
	 */
	public function actionView($id) {
		if (Yii::$app->getRequest()->isAjax) {
			return $this->renderAjax('view', [
						'model' => $this->findModel($id),
			]);
		} else {
			return $this->render('view', [
						'model' => $this->findModel($id),
			]);
		}
	}

	/**
	 * Creates a new CoreFields model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate() {
		if (Yii::$app->getRequest()->isAjax) {
			$model = new CoreFields();
			
			if ($model->load(Yii::$app->request->post())) {
				Yii::$app->response->format = Response::FORMAT_JSON;
				
				if ($model->save()) {
					$result = [
						'status' => 'success',
						'action' => 'create',
						'message' => Html::getMsgSuccess() . Yii::t('app', 'Data completed.'),
						'data' => $model,
					];
					return $result;
				} else {
					$result = [
						'status' => 'error',
						'message' => Html::getMsgError() . Yii::t('app', 'Can not create the data.'),
						'data' => $model,
					];
					return $result;
				}
			} else {
				return $this->renderAjax('create', [
							'model' => $model,
				]);
			}
		} else {
			throw new NotFoundHttpException('Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Updates an existing CoreFields model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param string $id
	 * @return mixed
	 */
	public function actionUpdate($id) {
		if (Yii::$app->getRequest()->isAjax) {
			$model = $this->findModel($id);
			
			if ($model->load(Yii::$app->request->post())) {
				Yii::$app->response->format = Response::FORMAT_JSON;
				
				if ($model->save()) {

					$result = [
						'status' => 'success',
						'action' => 'update',
						'message' => Html::getMsgSuccess() . Yii::t('app', 'Data completed.'),
						'data' => $model,
					];
					return $result;
				} else {
					$result = [
						'status' => 'error',
						'message' => Html::getMsgError() . Yii::t('app', 'Can not update the data.'),
						'data' => $model,
					];
					return $result;
				}
			} else {
				return $this->renderAjax('update', [
							'model' => $model,
				]);
			}
		} else {
			throw new NotFoundHttpException('Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Deletes an existing CoreFields model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param string $id
	 * @return mixed
	 */
	public function actionDelete($id) {
		if (Yii::$app->getRequest()->isAjax) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			if ($this->findModel($id)->delete()) {
				$result = [
					'status' => 'success',
					'action' => 'update',
					'message' => Html::getMsgSuccess() . Yii::t('app', 'Deleted completed.'),
					'data' => $id,
				];
				return $result;
			} else {
				$result = [
					'status' => 'error',
					'message' => Html::getMsgError() . Yii::t('app', 'Can not delete the data.'),
					'data' => $id,
				];
				return $result;
			}
		} else {
			throw new NotFoundHttpException('Invalid request. Please do not repeat this request again.');
		}
	}

	public function actionDeletes() {
		if (Yii::$app->getRequest()->isAjax) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			if (isset($_POST['selection'])) {
				foreach ($_POST['selection'] as $id) {
					$this->findModel($id)->delete();
				}
				$result = [
					'status' => 'success',
					'action' => 'deletes',
					'message' => Html::getMsgSuccess() . Yii::t('app', 'Deleted completed.'),
					'data' => $_POST['selection'],
				];
				return $result;
			} else {
				$result = [
					'status' => 'error',
					'message' => Html::getMsgError() . Yii::t('app', 'Can not delete the data.'),
					'data' => $id,
				];
				return $result;
			}
		} else {
			throw new NotFoundHttpException('Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Finds the CoreFields model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param string $id
	 * @return CoreFields the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id) {
		if (($model = CoreFields::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}

}

common/modules/yii2-core/views/core-fields/_form.php
<?php

use msoft\widgets\ActiveForm;
use msoft\helpers\Noty;
use msoft\helpers\Html;
use msoft\widgets\CheckboxX;
/* @var $this yii\web\View */
/* @var $model backend\modules\core\models\CoreFields */
/* @var $form yii\bootstrap\ActiveForm */
?>

<div class="core-fields-form">

    <?php $form = ActiveForm::begin([
		'id'=>$model->formName(),
    ]); ?>
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	    <h4 class="modal-title" id="itemModalLabel">Core Fields</h4>
	</div>

	<div class="modal-body">
	    <div class="row">
			<div class="col-md-6">
				<?= $form->field($model, 'field_code')->textInput(['maxlength' => true]) ?>
			</div>
			<div class="col-md-6 sdbox-col" style="padding-top: 21px;">
				<?= $form->field($model, 'field_internal',['showLabels'=>false])->widget(CheckboxX::classname(), [
						'pluginOptions'=>['threeState'=>false],
						'labelSettings' => [
								'label' => $model->getAttributeLabel('field_internal'),
								'position' => CheckboxX::LABEL_RIGHT
						]
				]);  ?>
			</div>
		
	    </div>
	    <div class="row">
			<div class="col-md-6">
				<?= $form->field($model, 'field_class')->textInput(['maxlength' => true,
					'placeholder' => !empty($model['field_class']) ? $model['field_class'] : 'msoft\widgets\ExampleWidgets::classname()',
				])->label('Widget Class') ?>
			</div>
			<div class="col-md-6 sdbox-col">
				<?= $form->field($model, 'field_name')->textInput(['maxlength' => true]) ?>
			</div>
		
	    </div>

		<?= $form->field($model, 'field_meta')->textarea(['rows' => 3]) ?>
	    
		<?= $form->field($model, 'field_description')->textarea(['rows' => 3]) ?>
	    
	</div>
	<div class="modal-footer">
	    <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-danger']) ?>
			<?= Html::button('Close', ['class' => 'btn btn-default','data-dismiss' => 'modal']) ?>
	</div>

    <?php ActiveForm::end(); ?>

</div>

<?php  $this->registerJs("
$('form#{$model->formName()}').on('beforeSubmit', function(e){
    var \$form = $(this);
    $.post(
		\$form.attr('action'), //serialize Yii2 form
		\$form.serialize()
    ).done(function(result){
		if(result.status == 'success'){
			". Noty::show('result.message', 'result.status') ."
			if(result.action == 'create'){
				$(\$form).trigger('reset');
				$.pjax.reload({container:'#core-fields-grid-pjax'});
			} else if(result.action == 'update'){
				$(document).find('#modal-core-fields').modal('hide');
				$.pjax.reload({container:'#core-fields-grid-pjax'});
			}
		} else{
			". Noty::show('result.message', 'result.status') ."
		} 
    }).fail(function(){
		". Noty::show("'" . Html::getMsgError() . "Server Error'", '"error"') ."
		console.log('server error');
    });
    return false;
});

");?>

common/modules/yii2-core/views/core-fields/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\core\models\CoreFieldsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="core-fields-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'field_code') ?>

    <?= $form->field($model, 'field_internal') ?>

    <?= $form->field($model, 'field_class') ?>

    <?= $form->field($model, 'field_name') ?>

    <?= $form->field($model, 'field_meta') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

common/modules/yii2-core/views/core-fields/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\core\models\CoreFields */

$this->title = Yii::t('core', 'Create Core Fields');
$this->params['breadcrumbs'][] = ['label' => Yii::t('core', 'Core Fields'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="core-fields-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

common/modules/yii2-core/views/core-fields/index.php
<?php

use yii\widgets\Pjax;
use yii\helpers\Url;
use msoft\widgets\GridView;
use msoft\core\widgets\ModalForm;
use msoft\helpers\Noty;
use msoft\helpers\Html;
use msoft\core\assets\CoreAsset;

CoreAsset::register($this);
$this->title = Yii::t('core', 'Core Widgets');
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
.modal-dialog {
    width: 99%;
}
</style>
<div class="core-fields-index">

    <div class="sdbox-header">
		<h3><?=  Html::encode($this->title) ?></h3>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

	<?php /*
    <p style="padding-top: 10px;">
		<span class="label label-primary">Notice</span>
		<?= Yii::t('app', 'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.') ?>
    </p>
	*/ ?>
	
    <?php  Pjax::begin(['id'=>'core-fields-grid-pjax']);?>
    <?= GridView::widget([
		'id' => 'core-fields-grid',
		'panel' => [
        	'heading'=> false,
			'before'=>	Html::button(Html::getBtnAdd(), ['data-url'=>Url::to(['core-fields/create']), 'class' => 'btn btn-success btn-sm', 'id'=>'modal-addbtn-core-fields']). ' ' .
						Html::button(Html::getBtnDelete(), ['data-url'=>Url::to(['core-fields/deletes']), 'class' => 'btn btn-danger btn-sm', 'id'=>'modal-delbtn-core-fields', 'disabled'=>true]),
			'after'=>false,
		],
		// 'panelBtn' => Html::button(Html::getBtnAdd(), ['data-url'=>Url::to(['core-fields/create']), 'class' => 'btn btn-success btn-sm', 'id'=>'modal-addbtn-core-fields']). ' ' .
		// 			  Html::button(Html::getBtnDelete(), ['data-url'=>Url::to(['core-fields/deletes']), 'class' => 'btn btn-danger btn-sm', 'id'=>'modal-delbtn-core-fields', 'disabled'=>true]),
		'dataProvider' => $dataProvider,
		'filterModel' => $searchModel,
		'hover' => true,
		'pjax' => true,
		'condensed' => true,
		'export' => [
			'fontAwesome' => true
		],
		'columns' => [
			[
				'class' => 'msoft\widgets\grid\CheckboxColumn',
				'checkboxOptions' => [
					'class' => 'selectionCoreFieldIds'
				],
				'headerOptions' => ['style'=>'text-align: center;'],
				'contentOptions' => ['style'=>'width:40px;text-align: center;'],
			],
			[
				'class' => 'yii\grid\SerialColumn',
				'headerOptions' => ['style'=>'text-align: center;'],
				'contentOptions' => ['style'=>'width:60px;text-align: center;'],
			],
			[
				'attribute'=>'field_code',
				'contentOptions'=>['style'=>'width:160px;'],
			],
			[
				'attribute'=>'field_internal',
				'value'=>function ($data){return ($data['field_internal']===1)?'Yes':'No';},
				'headerOptions'=>['style'=>'text-align: center;'],
				'contentOptions'=>['style'=>'width:60px;text-align: center;'],
				'filter'=>Html::activeDropDownList($searchModel, 'field_internal', [1=>'Yes', 0=>'No'], ['class'=>'form-control', 'prompt'=>'All']),
			],
			'field_class',
			'field_name',
			[
                'class' => 'msoft\widgets\ActionColumn',
                'template'=>'<div class="btn-group btn-group-sm" style="width:100px;"> {view} {update} {delete} </div>',
                'viewOptions' => [
					'class' => 'btn btn-sm btn-default',
					'data-action' => 'view',
                ],
                'updateOptions' => [
					'class' => 'btn btn-sm btn-default',
					'data-action' => 'update'
                ],
                'deleteOptions' => [
					'class' => 'btn btn-sm btn-default',
					'data-action' => 'delete'
				],
            ],
		],
	]); ?>
    <?php  Pjax::end();?>

</div>
<?=  ModalForm::widget([
    'id' => 'modal-core-fields',
    'size'=>'modal-lg',
]);
?>

<?php  $this->registerJs("
$('#core-fields-grid-pjax').on('click', '#modal-addbtn-core-fields', function(){
    modalCoreField($(this).attr('data-url'));
});

$('#core-fields-grid-pjax').on('click', '#modal-delbtn-core-fields', function(){
    selectionCoreFieldGrid($(this).attr('data-url'));
});

$('#core-fields-grid-pjax').on('click', '.select-on-check-all', function(){
    window.setTimeout(function() {
		var key = $('#core-fields-grid').yiiGridView('getSelectedRows');
		disabledCoreFieldBtn(key.length);
    },100);
});

$('#core-fields-grid-pjax').on('click', '.selectionCoreFieldIds', function(){
    var key = $('input:checked[class=\"'+$(this).attr('class')+'\"]');
    disabledCoreFieldBtn(key.length);
});

$('#core-fields-grid-pjax').on('dblclick', 'tbody tr', function() {
    var id = $(this).attr('data-key');
    modalCoreField('".Url::to(['core-fields/update', 'id'=>''])."'+id);
});	

$('#core-fields-grid-pjax').on('click', 'tbody tr td a', function() {
    var url = $(this).attr('href');
    var action = $(this).attr('data-action');

    if(action === 'update' || action == 'view'){
		modalCoreField(url);
    } else if(action === 'delete') {
		yii.confirm('".Yii::t('app', 'Are you sure you want to delete this item?')."', function(){
			$.post(
				url
			).done(function(result){
			if(result.status == 'success'){
				". Noty::show('result.message', 'result.status') ."
				$.pjax.reload({container:'#core-fields-grid-pjax'});
			} else {
				". Noty::show('result.message', 'result.status') ."
			}
			}).fail(function(){
				". Noty::show("'" . Html::getMsgError() . "Server Error'", '"error"') ."
				console.log('server error');
			});
		})
    }
    return false;
});

function disabledCoreFieldBtn(num){
    if(num>0){
		$('#modal-delbtn-core-fields').attr('disabled', false);
    } else{
		$('#modal-delbtn-core-fields').attr('disabled', true);
    }
}

function selectionCoreFieldGrid(url){
    yii.confirm('".Yii::t('app', 'Are you sure you want to delete these items?')."', function(){
		$.ajax({
			type: 'POST',
			url: url,
			data: $('.selectionCoreFieldIds:checked[name=\"selection[]\"]').serialize(),
			dataType: 'JSON',
			success: function(result) {
				if(result.status == 'success') {
					". Noty::show('result.message', 'result.status') ."
					$.pjax.reload({container:'#core-fields-grid-pjax'});
				} else {
					". Noty::show('result.message', 'result.status') ."
				}
			}
		})
	
    })
}

function modalCoreField(url) {
    $('#modal-core-fields .modal-content').html('<div class=\"sdloader \"><i class=\"sdloader-icon\"></i></div>');
    $('#modal-core-fields').modal('show')
    .find('.modal-content')
    .load(url);
}

");?>

common/modules/yii2-core/views/core-fields/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\core\models\CoreFields */

$this->title = Yii::t('core', 'Update {modelClass}: ', [
    'modelClass' => 'Core Fields',
]) . ' ' . $model->field_code;
$this->params['breadcrumbs'][] = ['label' => Yii::t('core', 'Core Fields'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->field_code, 'url' => ['view', 'id' => $model->field_code]];
$this->params['breadcrumbs'][] = Yii::t('core', 'Update');
?>
<div class="core-fields-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

common/modules/yii2-core/views/core-fields/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\modules\core\models\CoreFields */

$this->title = 'Core Fields#'.$model->field_code;
$this->params['breadcrumbs'][] = ['label' => Yii::t('core', 'Core Fields'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="core-fields-view">

    <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title" id="itemModalLabel"><?= Html::encode($this->title) ?></h4>
    </div>
    <div class="modal-body">
        <?= DetailView::widget([
			'model' => $model,
			'attributes' => [
				'field_code',
				'field_internal',
				'field_class',
				'field_name',
				'field_meta:ntext',
				'field_description:ntext',
			],
		]) ?>
    </div>
</div>